### ISSUE TITLE
ReSpeaker 2-Mics with stereo speakers

### ISSUE THREAD

**Issue by dubaleeiro** [respeaker/seeed-voicecard#139]
Hi, what is the best war to connect 2x 5W 8 Ohm speakers to the board? Audio JAC? GPIO pins? JST audio connector is just for mono speakers...
Thank you!

**Comment by Pillar1989** [comment]
AUX interface support stereo speakers, audio connector is just for mono speakers

**Comment by dubaleeiro** [comment]
Hi, which one you mean AUX interface? The JST speaker out or 3.5mm Audio JAC? Thank you!

**Comment by dubaleeiro** [comment]
Dear @Pillar1989, could you please  explain again how I can connect stereo speakers? Thank you

**Comment by Pillar1989** [comment]
3.5mm Audio JAC

**Comment by ebs54** [comment]
Hi, I like to use the ReSpeaker 2-Mics in a Raspberry Pi zero W with Volumio OS. The Assistent can select varios types of HAT but not the ReSpeaker 2-Mics. 
Can you help me?
Thanks
Ebs

**Comment by dubaleeiro** [comment]
Same here! I have sent an email to them but so far I got no answer...

**Comment by Pillar1989** [comment]
What is Volumio OS? I did not see this release in http://www.raspberrypi.org

**Comment by ebs54** [comment]
See volumio.orgAm 25.03.2019 02:47 schrieb Baozhu Zuo <notifications@github.com>:What is Volumio OS? I did not see this release in http://www.raspberrypi.org

**Comment by Pillar1989** [comment]
So wouldn't it be better to discuss this with https://volumio.org/forum/ ?

**Comment by ebs54** [comment]
There I could not find your pHAT.If your pHAT is compatible with an other well known, this is very helpfull.      Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Baozhu Zuo <notifications@github.com> Datum: 25.03.19  07:29  (GMT+01:00) An: respeaker/seeed-voicecard <seeed-voicecard@noreply.github.com> Cc: ebs54 <oneway4key@t-online.de>, Comment <comment@noreply.github.com> Betreff: Re: [respeaker/seeed-voicecard] ReSpeaker 2-Mics with stereo speakers
  (#139) So wouldn't it be better to discuss this with https://volumio.org/forum/ ?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/respeaker/seeed-voicecard","title":"respeaker/seeed-voicecard","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/respeaker/seeed-voicecard"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Pillar1989 in #139: So wouldn't it be better to discuss this with https://volumio.org/forum/ ? "}],"action":{"name":"View Issue","url":"https://github.com/respeaker/seeed-voicecard/issues/139#issuecomment-476070977"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/respeaker/seeed-voicecard/issues/139#issuecomment-476070977",
"url": "https://github.com/respeaker/seeed-voicecard/issues/139#issuecomment-476070977",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
