### ISSUE TITLE
FAQ Link expired

### ISSUE THREAD

**Issue by tomh05** [respeaker/seeed-voicecard#266]
At the bottom of README.md, the link to the raspberry pi image gives this message:

> Support for the company which the current shared item is in has been expired. Please contact the share link owner.

**Comment by bennoheld** [comment]
This is actually quite frustrating, because according to the README this should be the first approach to solving problems. Please update as soon as possible!

**Comment by fraserabrown** [comment]
+1. please fix this or provide another download link. i have bought a mic array which i cannot use.

**Comment by AIWintermuteAI** [comment]
Re-uploaded fresh image.
https://github.com/respeaker/seeed-voicecard#technical-support

**Keep in mind, that the image is made only for hardware testing purposes** - it won't be frequently updated, since recommended way of using reSpeaker is to install drivers from this repository.
Closing the issue.
