### ISSUE TITLE
asound.conf gets overwritten  by /usr/bin/seeed-voicecard

### ISSUE THREAD

**Issue by faaafo** [respeaker/seeed-voicecard#293]
asound.conf gets overwritten  by /usr/bin/seeed-voicecard on each reboot. Had to comment out these lines:

`rm /etc/asound.conf` and `ln -s $asound_conf /etc/asound.conf`

in order to keep **b1** from getting overwritten with **ALSA**
```conf
pcm.playback {
    type plug
    slave.pcm "plughw:b1"
}
```
Where is that documented?

**Comment by AIWintermuteAI** [comment]
hi @faaafo !
This is done in order to prevent conflicts between existing sound configuration and configuration necessary for reSpeaker to work correctly. While it is not the best solution, it is not possible to automatically merge user configuration with reSpeaker specific configuration. 

Advanced users can comment these two lines and edit their asound.conf manually. I'll add this to reSpeaker FAQ on Seeed Wiki.
